'use client'
import type { Metadata } from 'next'
import './globals.css'
import { SnackbarProvider } from 'notistack'

const metadata: Metadata = {
  title: 'Bottled Clarity',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SnackbarProvider
          anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        >
          {children}
        </SnackbarProvider>
      </body>
    </html>
  )
}
